"""One-time setup so the mod can launch the dashboard from inside Balatro.

    python ingest/install.py

Does two things:

1. Links this repo's mod into Balatro's Mods folder, if it is not already.
2. Writes a launcher script next to the run logs, recording the absolute paths
   to this Python and to dashboard.py.

The second exists because the mod cannot work out where this repo is. It sees
itself at <save dir>/Mods/BalatroDB, and on Windows `..` from a junction
resolves against the junction's own path rather than its target -- so walking
up from there lands back in Mods, not in the repo. (A POSIX symlink does not
have that problem, but the mod should not have to care which it is looking
through.) Rather than guess, setup records the answer somewhere the mod
already knows how to read: the BalatroDB data directory, beside the logs.

Windows, macOS and Linux. Where they differ -- how you link a directory
without administrator rights, and what a detached launcher looks like -- the
two branches are side by side below.
"""
from __future__ import annotations

import argparse
import os
import stat
import subprocess
import sys

import paths

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
MOD_SRC = os.path.join(REPO, "mod", "BalatroDB")
MOD_DST = os.path.join(paths.MODS_DIR, "BalatroDB")


def link_mod() -> str:
    if os.path.exists(MOD_DST) or os.path.islink(MOD_DST):
        return f"already linked: {MOD_DST}"
    if not os.path.isdir(paths.MODS_DIR):
        return (f"SKIPPED: no Mods folder at {paths.MODS_DIR}"
                " (is Steamodded installed?)")
    if paths.WINDOWS:
        # A junction rather than a symlink: symlinks need administrator
        # rights on Windows, junctions do not, and Steamodded's scan accepts
        # either.
        r = subprocess.run(["cmd", "/c", "mklink", "/J", MOD_DST, MOD_SRC],
                           capture_output=True, text=True)
        if r.returncode:
            return f"FAILED to link: {r.stderr.strip() or r.stdout.strip()}"
    else:
        # Symlinks are unprivileged everywhere else, so there is nothing to
        # work around.
        try:
            os.symlink(MOD_SRC, MOD_DST, target_is_directory=True)
        except OSError as ex:
            return f"FAILED to link: {ex}"
    return f"linked {MOD_DST} -> {MOD_SRC}"


def write_launcher(port: int) -> str:
    os.makedirs(paths.DATA_DIR, exist_ok=True)
    dash = os.path.join(HERE, "dashboard.py")
    # Both forms detach, so the game is never left waiting on os.execute.
    # dashboard.py opens the browser itself, and exits quietly if a server is
    # already listening -- so pressing the button twice is harmless.
    if paths.WINDOWS:
        body = (
            "@echo off\r\n"
            "rem Generated by ingest/install.py -- launches the BalatroDB dashboard.\r\n"
            f'start "BalatroDB" /MIN "{sys.executable}" "{dash}" --port {port}\r\n'
        )
        newline = ""
    else:
        # nohup so it outlives the shell the game spawned, and the output
        # goes nowhere: there is no terminal attached to read it.
        body = (
            "#!/bin/sh\n"
            "# Generated by ingest/install.py -- launches the BalatroDB dashboard.\n"
            f'nohup "{sys.executable}" "{dash}" --port {port}'
            " >/dev/null 2>&1 &\n"
        )
        newline = "\n"
    with open(paths.LAUNCHER, "w", encoding="utf-8", newline=newline) as fh:
        fh.write(body)
    if not paths.WINDOWS:
        # It is run as `sh <path>`, which does not need the bit -- but a
        # launcher you cannot also double-click is a worse launcher.
        mode = os.stat(paths.LAUNCHER).st_mode
        os.chmod(paths.LAUNCHER, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return f"wrote {paths.LAUNCHER}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, default=8611)
    a = ap.parse_args()

    if not os.path.isdir(paths.SAVE_DIR):
        print(f"No Balatro save directory at {paths.SAVE_DIR}.")
        print("Run the game once first, or pass the right HOME/APPDATA.")
        return 1

    print(link_mod())
    print(write_launcher(a.port))
    print()
    print("Restart Balatro. A BalatroDB button will appear in the Options menu;")
    print("pressing it starts the dashboard and opens it in your browser.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
