"""One-time setup so the mod can launch the dashboard from inside Balatro.

    python ingest/install.py

Does two things:

1. Links this repo's mod into Balatro's Mods folder, if it is not already.
2. Writes a launcher script next to the run logs, recording the absolute paths
   to this Python and to dashboard.py.

The second exists because the mod cannot work out where this repo is. It sees
itself at `<save dir>/Mods/BalatroDB`, and on Windows `..` from a junction
resolves against the junction's own path rather than its target -- so walking
up from there lands back in Mods, not in the repo. Rather than guess, setup
records the answer somewhere the mod already knows how to read: the BalatroDB
data directory, beside the logs.

The launcher is a .bat on Windows and a .sh everywhere else; menu.lua picks
the matching name by OS. The save directory itself is per-platform -- see
paths.py.
"""
from __future__ import annotations

import argparse
import os
import shlex
import subprocess
import sys

import paths

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
MOD_SRC = os.path.join(REPO, "mod", "BalatroDB")

WINDOWS = sys.platform == "win32"
MODS_DIR = paths.mods_dir()
MOD_DST = os.path.join(MODS_DIR, "BalatroDB")
DATA_DIR = paths.data_dir()
LAUNCHER = os.path.join(DATA_DIR, "launch-dashboard." + ("bat" if WINDOWS else "sh"))


def link_mod() -> str:
    if os.path.exists(MOD_DST):
        return f"already linked: {MOD_DST}"
    if not os.path.isdir(MODS_DIR):
        return f"SKIPPED: no Mods folder at {MODS_DIR} (is Steamodded installed?)"
    if not WINDOWS:
        # A plain symlink needs no special rights outside Windows.
        try:
            os.symlink(MOD_SRC, MOD_DST)
        except OSError as exc:
            return f"FAILED to link: {exc}"
        return f"linked {MOD_DST} -> {MOD_SRC}"
    # A junction rather than a symlink: symlinks need administrator rights on
    # Windows, junctions do not, and Steamodded's scan accepts either.
    r = subprocess.run(["cmd", "/c", "mklink", "/J", MOD_DST, MOD_SRC],
                       capture_output=True, text=True)
    if r.returncode:
        return f"FAILED to link: {r.stderr.strip() or r.stdout.strip()}"
    return f"linked {MOD_DST} -> {MOD_SRC}"


def write_launcher(port: int) -> str:
    os.makedirs(DATA_DIR, exist_ok=True)
    dash = os.path.join(HERE, "dashboard.py")
    # Both forms detach, so the game is not left waiting on os.execute:
    # `start ""` on Windows, a backgrounded nohup elsewhere. dashboard.py
    # opens the browser itself, and exits quietly if a server is already
    # listening -- so pressing the button twice is harmless.
    if WINDOWS:
        body = (
            "@echo off\r\n"
            "rem Generated by ingest/install.py -- launches the BalatroDB dashboard.\r\n"
            f'start "BalatroDB" /MIN "{sys.executable}" "{dash}" --port {port}\r\n'
        )
    else:
        body = (
            "#!/bin/sh\n"
            "# Generated by ingest/install.py -- launches the BalatroDB dashboard.\n"
            f"nohup {shlex.quote(sys.executable)} {shlex.quote(dash)} --port {port}"
            " >/dev/null 2>&1 &\n"
        )
    with open(LAUNCHER, "w", encoding="utf-8", newline="") as fh:
        fh.write(body)
    return f"wrote {LAUNCHER}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, default=8611)
    a = ap.parse_args()

    if WINDOWS and not os.environ.get("APPDATA"):
        print("APPDATA is not set; cannot find Balatro's save folder.")
        return 1

    print(link_mod())
    print(write_launcher(a.port))
    print()
    print("Restart Balatro. A BalatroDB button will appear under Options;")
    print("pressing it starts the dashboard and opens it in your browser.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
